### ISSUE TITLE
Docs suggest mask takes an integer but only a string works.

### ISSUE THREAD

**Issue by trenta** [puppetlabs/puppetlabs-acl#260]
## Describe the Change You Would Like
I tried:
`{ identity => 'tanderson', rights => ['mask_specific'], mask => 511}`
Which errored with:
```
Error: Failed to apply catalog: Parameter permissions failed on Acl[F:\Shares\groups\SVI-SOFTDIST\Trent]: Munging failed for value {"identity"=>"tanderson", "rights"=>["mask_specific"], "mask"=>511} in class permissions: undefined method `empty?' for 511:Integer (file: /etc/puppetlabs/code/environments/production/site/profile/manifests/fileservers/groups.pp, line: 27)
```

I tried: 
`{ identity => 'tanderson', rights => ['mask_specific'], mask => '511'}`

which worked.

**Comment by pmcmaw** [comment]
@trenta a fix has been merged, please keep an eye out as this fix will be included in our next release. I also want to take the time to thank you for raising this issue and sharing your investigations. Closing this issue as Fixed.
