### ISSUE TITLE
Failed to set security descriptor for path, possible `inheriting_permissions` issue

### ISSUE THREAD

**Issue by cummingscody** [puppetlabs/puppetlabs-acl#262]
## Describe the Bug
When trying to set an ACL with the below snippet a client is getting a "Failed to set security descriptor for path" error.
`
acl { $path :
  permissions                => $permissions,
  purge                      => true,
  inherit_parent_permissions => $inheritance,
  require                    => File[$path],
}
`

Full error:
`
2022-06-09 10:46:38 -0500 /Stage[main]/Nas_acl_management/Acl[\\epic-nas\Static\ABN] (err): Could not evaluate: Failed to set security descriptor for path '\\epic-nas\Static\ABN': Failed to set security information:  This security ID may not be assigned as the owner of this object. 
`

## Expected Behavior
It should set without erroring on ownership, as ownership was not specified.

## Steps to Reproduce
Add the snippet to a module and run puppet agent.

## Environment
Module version: 4.0.0
PE Version: 2021.4
Platform: Agent - Server 2012 R2

## Additional Context
Risen from support ticket #48281

**Comment by david22swan** [comment]
Forgot to update this sorry.
Unable to replicate issue, so not much I can do

**Comment by LukasAud** [comment]
Cant replicate. Closing issue after confirmation from support.
